CREATE DATABASE IF NOT EXISTS deathstar;
USE deathstar;
CREATE TABLE IF NOT EXISTS user (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);
INSERT INTO user (name) VALUES ('John');
INSERT INTO user (name) VALUES ('Tom');